### ISSUE TITLE
libhardware_interface.so: undefined reference to `class_loader::ClassLoader::isLibraryLoaded()'

### ISSUE THREAD

**Issue by jainishmehta** [ros-controls/ros2_control#1025] opened 2023-05-16 21:43 UTC
**Describe the bug**

![image](https://github.com/ros-controls/ros2_control/assets/45054638/841214d4-8959-404a-a3d8-db9cfdd2e62a)

**To Reproduce**
1. GIt clone this repo. 
2. Run colcon build

**Expected behavior**
Should build correctly.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 Focal
 - Version Foxy
- Anything that may be unusual about your environment

**Additional context**
Need it to get webots_ros2_control pkg.

**Comment by bmagyar** [comment] 2023-05-17 10:37
![7m334c](https://github.com/ros-controls/ros2_control/assets/3524577/08bb82a5-6eb9-4220-9432-209ca9653d1c)

Make sure you use the appropriate branch & the correct installation. I'll close this issue as this is only a problem on your end, not a bug with the framework. Please seek further help on https://answers.ros.org/ or whoever gave you the instructions to compile anything from source in the first place :+1:

**Closed by bmagyar** 2023-05-17 10:37 UTC
