### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by JakeFishcode** [ros-controls/ros2_control#987] opened 2023-04-11 07:38 UTC
I am a beginner in ROS2 and I am trying to use ROS2 control humble on the Nvidia Orin kit running Jetson Linux. I have built a Docker container based on Ubuntu 20.04 and have compiled the source code for ROS2 Humble. However, I have encountered several dependency issues while trying to compile ROS2 control (humble branch) on Jetson Linux 35.1. I am using this version because it has hardware acceleration for humble.

Could you please suggest a way to resolve these dependency issues and compile ROS2 control humble on Ubuntu 20.04 by source code?

**Comment by bmagyar** [comment] 2023-04-11 10:43
So many things.

### Bug label
Please only use the bug label if you are 100% there's something wrong. The fact that something doesn't work for you is not a bug, it's a challenge you are facing today. Best is to not use the bug label at all.

### Issue title

"Help" is not helpful. If you expect people to spend their time helping you, put at least the work in to describe to them what your problem is. There are long descriptions to post as the issue body which you should be able to summarize in a meaningful way for the issue title. People read what you write. Write it in a way that they will want to read it.

### Asking for help

We have an issue template for a bug report that gives you a good template for submitting a structured "bug report" (even if it is not a bug) which guides you how to write something that others can make sense of and produce some answer that is useful to you. I'll post it here for you:

```
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment (please complete the following information):**
 - OS: [e.g. iOS]
 - Version [e.g. Foxy]
- Anything that may be unusual about your environment

**Additional context**
Add any other context about the problem here, especially include any modifications to ros2_control that relate to this issue.
```

**Comment by destogl** [comment] 2023-04-11 10:50
@JakeFishcode your bug is not a bug is the issue that you are trying to compile humble on 20.04. This does not work and it will never work. humble targets 22.04

**Comment by destogl** [comment] 2023-04-11 10:50
Closing because it is not relevant / wrong.

**Closed by destogl** 2023-04-11 10:50 UTC
Labels: question
