### ISSUE TITLE
Galactic: ros2_control + gazebo_ros2_control

### ISSUE THREAD

**Issue by cco-seasony** [ros-controls/ros2_control#550] opened 2021-10-11 12:36 UTC
Hi!
I know it is not the right repo BUT I few months ago I opened an [issue](https://github.com/ros-simulation/gazebo_ros2_control/issues/84) and I have not received any answers. 
I was wondering if anyone here knew the status of gazebo_ros2_control for Galactic. Is it something that is being worked on?
Thanks in advance for the help!

**Comment by AureoGD** [comment] 2021-10-19 13:24
Hi!
A quick update:  yesterday I followed the steps described, and after some additional changes at Update method in the gazebo_ros2_control_plugin.cpp file, I could build the package. Then I executed the examples, but the Gazebo did not respond to the commands (at least, it is not possible to observe the joint movement). I will keep trying to find the cause of the problem.

**Comment by destogl** [comment] 2022-01-27 12:58
@cco-seasony is this still a thing? If not please close this issue.

**Closed** 2022-01-28 07:51 UTC
